name: Cypress E2E

on:
  push:
    branches: [staging]

env:
  STAGING_BASE_URL_SECRET_NAME: STAGING_BASE_URL

jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '18'
      - name: Install deps
        run: |
          npm ci
      - name: Run Cypress smoke tests
        env:
          CYPRESS_BASE_URL: ${{ secrets[env.STAGING_BASE_URL_SECRET_NAME] }}
        run: |
          npx cypress run --config baseUrl="$CYPRESS_BASE_URL"
