name: Cypress E2E

on:
  push:
    branches: [staging]

jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '18'
      - name: Install deps
        run: |
          npm ci
      - name: Run Cypress smoke tests
        env:
          CYPRESS_BASE_URL: ${{ secrets.STAGING_BASE_URL }}
        run: |
          npx cypress run --config baseUrl=${{ secrets.STAGING_BASE_URL }}
